//
//  UIColor+CNTAdditions.swift
//
//  Generated by Zeplin on 1/31/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var cntJungleGreen: UIColor {
		return UIColor(red: 0.0, green: 121.0 / 255.0, blue: 84.0 / 255.0, alpha: 1.0)
	}
}
