//
//  UIFont+CNTAdditions.swift
//
//  Generated by Zeplin on 1/31/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func cntTextStyleFont() -> UIFont? {
		return UIFont(name: "HelveticaNeue-Bold", size: 68.0)
	}

	class func cntCountFont() -> UIFont? {
		return UIFont(name: "HelveticaNeue-Bold", size: 54.0)
	}

	class func cntMotivationFont() -> UIFont? {
		return UIFont(name: "HelveticaNeue-MediumItalic", size: 20.0)
	}
}
